### ISSUE TITLE
Is there a reason why we are not using latest Maven 3.3.3?

### ISSUE THREAD

**Issue by alberttwong** [jbossdemocentral/jboss-fuse-mqgateway-failoverdemo#2]
I can downgrade but was there a specific reason?

**Comment by weimeilin79** [comment]
It's because from 3.2.5 there has been a Major API change. 
And our product does not support it yet. 
See. 
http://wei-meilin.blogspot.tw/2015/07/jboss-fuse-tips-deploying-profile.html
