### ISSUE TITLE
Why is that run you run ./bin/stop, there are still java processes running? 

### ISSUE THREAD

**Issue by alberttwong** [jbossdemocentral/jboss-fuse-mqgateway-failoverdemo#8]
I want to shutdown the server. I ran ./bin/stop and after several minutes I did a "ps -ef" and I still see java processes running.  Is there a way to shut all of it down?

**Comment by weimeilin79** [comment]
If you run the stop command, it only shutdowns down the root container, you will need to stop your child container before you shutdown the root container. 
Or  use this command to kill them all. 
jps -lm | grep karaf | grep -v grep | awk '{print $1}' | xargs kill -KILL

**Comment by alberttwong** [comment]
This doesn't seem to be ideal (confusing for customers).  Are there plans to enhance stop shutdown root and all the children?

**Comment by weimeilin79** [comment]
Not a good idea, because in real production, sometime we want to shutdown the root container for maintenance, but keeping the child running so it doesn't affect running services.

**Comment by alberttwong** [comment]
Found out from development.   Correct way to shut down fuse containers is "./bin/admin stop container-name".  killing process may mess with application shutdown processes.  I'll update docs.
